
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueWS", targetNamespace = "http://services.ayoub.sakine/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convert", targetNamespace = "http://services.ayoub.sakine/", className = "proxy.Convert")
    @ResponseWrapper(localName = "convertResponse", targetNamespace = "http://services.ayoub.sakine/", className = "proxy.ConvertResponse")
    @Action(input = "http://services.ayoub.sakine/BanqueWS/convertRequest", output = "http://services.ayoub.sakine/BanqueWS/convertResponse")
    public double convert(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://services.ayoub.sakine/", className = "proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://services.ayoub.sakine/", className = "proxy.GetCompteResponse")
    @Action(input = "http://services.ayoub.sakine/BanqueWS/getCompteRequest", output = "http://services.ayoub.sakine/BanqueWS/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "comptes", targetNamespace = "http://services.ayoub.sakine/", className = "proxy.Comptes")
    @ResponseWrapper(localName = "comptesResponse", targetNamespace = "http://services.ayoub.sakine/", className = "proxy.ComptesResponse")
    @Action(input = "http://services.ayoub.sakine/BanqueWS/comptesRequest", output = "http://services.ayoub.sakine/BanqueWS/comptesResponse")
    public List<Compte> comptes();

}
